language: node_js

if: tag IS present

node_js:
- '10'

os: osx

cache:
  directories:
  - '$HOME/.electron'
  - "node_modules"

install:
- npm install -g npm
- npm install
- npm update

script:
- npm run build

deploy:
  provider: releases
  api_key: '$GITHUB_TOKEN'
  file_glob: true
  draft: true
  file: 'release-builds/KCModManager-*-mac.zip'
  bucket: "kcmodmanager"
  skip_cleanup: true
  on:
    tags: true